### ISSUE TITLE
Authy not accepted

### ISSUE THREAD

**Issue by parkerlreed** [MayeulC/hb-downloader#5]
Latest git

````
[2018/04/18 03:45:10] [    Config] write_md5=True
[2018/04/18 03:45:10] [    Config] read_md5=True
[2018/04/18 03:45:10] [    Config] force_md5=False
[2018/04/18 03:45:10] [    Config] ignore_md5=False
[2018/04/18 03:45:10] [    Config] debug=True
[2018/04/18 03:45:10] [    Config] download_location=/home/parker/backup
[2018/04/18 03:45:10] [    Config] cookie_filename=cookies.txt
[2018/04/18 03:45:10] [    Config] chunksize=8192000
[2018/04/18 03:45:10] [    Config] resume_downloads=True
[2018/04/18 03:45:10] [    Config] Platform audio=False
[2018/04/18 03:45:10] [    Config] Platform ebook=False
[2018/04/18 03:45:10] [    Config] Platform windows=False
[2018/04/18 03:45:10] [    Config] Platform mac=False
[2018/04/18 03:45:10] [    Config] Platform linux=True
[2018/04/18 03:45:10] [    Config] Platform android=True
[2018/04/18 03:45:10] [    Config] Platform asmjs=False
Enter your Authy token: <authycode>
Traceback (most recent call last):
  File "./hb-downloader.py", line 41, in <module>
    hapi.login(ConfigData.username, ConfigData.password, ConfigData.authy_token)
  File "/home/parker/build/hb-downloader/humble_api/humble_api.py", line 137, in login
    error_msg, request=request, response=response, authy_required=authy_required)
humble_api.exceptions.humble_captcha_exception.HumbleCaptchaException: Are you sure you're not a robot? Please try again.
````

**Comment by parkerlreed** [comment]
I only found the project recently from your comment elsewhere so I'm not sure of how recent the error is. 

I will try the simple auth.

Don't remember how big mine actually is. I'm only downloading Linux/Android so I'll let you know.

**Comment by parkerlreed** [comment]
![screenshot from 2018-04-19 17-11-18](https://user-images.githubusercontent.com/841440/39018692-c8f72480-43f4-11e8-8bf4-2eddd2331868.png)

Ran fine. I had to reboot for something else and it resumed nicely afterwards. Checked all the checksums and continued on.

**Comment by parkerlreed** [comment]
````
./hb-downloader.py -c "<cookie>" download
````

I ran that on the next branch and it just listed my purchases and exited.

**Comment by MayeulC** [comment]
Mmm... it should have downloaded everything. The command line is not clear, but download is optional, as it will bypass configuration. Thanks for reporting, I will investigate!

**Comment by parkerlreed** [comment]
Ahh thanks. I just did that on the command line since I've had to relogin a few times on the browser side. Was just easier for me to paste it on the command line.

I'll give it another go.

**Comment by parkerlreed** [comment]
Cheers. That fixed it!
